default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: webcon_development
  host: localhost
  username: <%= ENV["RAILS_DATABASE_USER"] %>
  password: <%= ENV["RAILS_DATABASE_PASSWORD"] %>


test:
  <<: *default
  encoding: unicode
  database: webcon_test
  host: localhost
  username: <%= ENV["RAILS_DATABASE_USER"] %>
  password: <%= ENV["RAILS_DATABASE_PASSWORD"] %>